#!/usr/bin/bash

output=$(hyprpicker -n -a -f hex)

if [[ $output =~ ^.*#([A-Fa-f0-9]{6})$ ]]; then
	color=$(wl-paste)
	image=/tmp/color.png
	magick -size 48x48 xc:"$color" ${image}
	notify-send -u low -i ${image} "$color" "Copied to clipboard"
fi
